name: flutter_provider
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  provider: ^6.0.2
  syncfusion_flutter_calendar: ^19.4.56
  intl: ^0.17.0
  flutter_colorpicker: ^1.0.3
  numberpicker: ^2.1.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_core: ^1.13.1
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
    - images/
